#!/bin/bash
# usage: find-convert-flv /source/dir
# use fcf.conf for further configuration

scriptTitle() {
scriptName="flvConverter"
scriptVersion="1.0"
scriptBuild="12062016"
scriptAuthor="Michael Matzat"
printf '%s\n\n';
eval printf %.0s- '{1..'"${COLUMNS:-$(tput cols)}"\}; echo
printf '%s\n' "		$scriptName $scriptVersion";
printf '%s\n' "		Build $scriptBuild";
printf '%s\n' "		Development by $scriptAuthor";
eval printf %.0s- '{1..'"${COLUMNS:-$(tput cols)}"\}; echo
printf '%s\n\n';
}

scriptTitle;
echo "cfgFile: $FCF_CFG"

CONFIG_FILE=`echo $FCF_CFG`;
source "$CONFIG_FILE";
if [ $? = 0 ]
then
fcflogV1 "INFO" "configFile" "OK";
else
fcflogV1 "ERROR" "configFile" "FAILED";
exit 1
fi

timestamp=$(date "+%d"."%m"."%Y %T")

# checking sourceDir
sourceDir="$1"
if [ -n "$1" ]
then
fcflogV1 "INFO" "arguments" "OK";
else
fcflogV1 "ERROR" "arguments" "FAILED";
exit 1
fi

if [ -d "$1" ]
then
fcflogV1 "INFO" "sourceFolder" "OK";
cd $scriptDir
else
fcflogV1 "ERROR" "sourceFolder" "FAILED";
exit 1
fi

# define converterClass
# $1 = filename     $2 = /path/to/folder
convertFile() {
sourceFileName="$1"
sourceDir="$2"
sourceFile="$2/$1.flv"
destFile="$2/$1.avi"
echo "flvFile: $sourceFile"

# progress indicator
spinner &
spinner_pid=$!
/usr/local/bin/ffmpeg -loglevel quiet -async 1 -i "$sourceFile" -f avi -b 700k -qscale 0 -ab 160k -ar 44100 "$destFile" &> /dev/null

# kill progress indicator
kill $spinner_pid &> /dev/null

if [ $? = 0 ]
then
fcflogV1 "INFO" "flvConvertion" "OK";
	case "$deleteFileAfterConvert" in
		yes)
		rm "$sourceFile"
		fcflogV1 "INFO" "remove sourceFile" "OK"
		;;
		no) fcflogV1 "INFO" "dont remove sourceFile" "OK"
		;;
		*) fcflogV1 "INFO" "dont remove sourceFile" "OK"
		;;
	esac
else
fcflogV1 "WARNING" "flvConvertion" "FAILED";
echo "skipping file: $fileName"
fi
}

# del/touch fcf.list
rm $listFile
touch $listFile
if [ $? = 0 ]
then
fcflogV1 "INFO" "create listFile" "OK";
else
fcflogV1 "ERROR" "create listFile" "FAILED";
exit 1
fi

# find .flv files in sourceDir and fill listFile
#find "$sourceDir/" -type f -name "*.flv" -exec echo '{}' >> $listFile \;
cd $sourceDir
ls -1 *.flv| cut -d . -f 1 >> $listFile
if [ $? = 0 ]
then
cd $scriptDir
fcflogV1 "INFO" "find .flv files" "OK";
fcflogV1 "INFO" "fill listFile" "OK";
else
cd $scriptDir
fcflogV1 "ERROR" "find .flv files" "FAILED";
fcflogV1 "ERROR" "fill listFile" "FAILED";
exit 1
fi

# read listFile
# fcflog "INFO" "listFile exist" "OK";
while IFS='' read -r fileName
do
	convertFile "$fileName" "$sourceDir"
done < "$listFile"

if [ $? = 0 ]
then
fcflogV1 "INFO" "reading listFile" "OK";
else
fcflogV1 "ERROR" "reading listFile" "FAILED";
exit 1
fi

exit 0