#!/bin/bash
# usage: find-convert-flv /source/dir
# use fcf.conf for further configuration

CONFIG_FILE=`echo $FCF_CFG`;
echo "INFO: found configFile > $FCF_CFG";
source "$CONFIG_FILE"
if [ $? = 0 ]
then
echo "INFO: loading configFile				${GREEN}[OK]$NONE"
else
echo "ERROR: loading configFile				${RED}[FAILED]$NONE"
echo "please check permission and path and env var!"
exit 1
fi

timestamp=$(date "+%d"."%m"."%Y %T")

# checking sourceDir
sourceDir="$1"
if [ -n $1 ]
then
fcflog "INFO" "sourceFolderVar					${GREEN}[OK]$NONE";
else 
fcflog "ERROR" "sourceFolderVar					${RED}[FAILED]$NONE";
echo "usage: find-convert-flv /path/to/folder/ "
exit 1
fi

if [ -d "$1" ]
then	
fcflog "INFO" "check sourceFolder				${GREEN}[OK]$NONE";
cd $scriptDir
else
fcflog "ERROR" "check sourceFolder				${RED}[FAILED]$NONE";
exit 1
fi

# define converterClass
# $1 = filename     $2 = /path/to/file
convertFile() {
sourceFileName=$1
sourceDir=$2
sourceFile="$2/$1.flv"
destFile="$2/$1.avi"
fcflog "INFO" "flv-convert started > $sourceFile";

# progress indocator
spinner & 
spinner_pid=$!
#################

/usr/local/bin/ffmpeg -loglevel quiet -async 1 -i "$sourceFile" -f avi -b 700k -qscale 0 -ab 160k -ar 44100 "$destFile" < /dev/null

# kill progress imdicator
kill $spinner_pid >/dev/null
#####################

if [ $? = 0 ]
then
fcflog "INFO" "flv-convert					${GREEN}[OK]$NONE";

  case "$deleteFileAfterConvert" in
     yes) 
     rm "$sourceFile"
     fcflog "INFO" "remove sourceFile					${GREEN}[OK]$NONE"
     ;;
     no)
     fcflog "INFO" "dont remove sourceFile					${GREEN}[OK]$NONE"
     ;;
     *) fcflog "INFO" "dont remove sourceFile					${GREEN}[OK]$NONE";;
  esac

else
fcflog "WARNING" "flv convertion					${RED}[FAILED]$NONE";
echo "skipping file > $fileName";
echo " "
fi
}

# del/touch fcf.list
rm $listFile && touch $listFile
if [ $? = 0 ]
then
fcflog "INFO" "create listFile					${GREEN}[OK]$NONE";
else
fcflog "ERROR" "create listFile					${RED}[FAILED]$NONE";
echo "please check permission and path and env var!"
exit 1
fi

# find .flv files in sourceDir and fill listFile
#find "$sourceDir/" -type f -name "*.flv" -exec echo '{}' >> $listFile \;
cd $sourceDir
'ls -1 *.flv| cut -d . -f 1 >> $listFile
if [ $? = 0 ]
then
cd $scriptDir
fcflog "INFO" "find .flv files					${GREEN}[OK]$NONE";
fcflog "INFO" "fill listFile					${GREEN}[OK]$NONE";
else
cd $scriptDir
fcflog "ERROR" "find .flv files					${RED}[FAILED]$NONE";
fcflog "ERROR" "fill listFile					${RED}[FAILED]$NONE";
echo "check if sourceDir exist and connection etablished!"
exit 1
fi

# read listFile
fcflog "INFO" "listFile exist					${GREEN}[OK]$NONE";
while IFS='' read -r fileName
do
	convertFile "$fileName" "$sourceDir";
done < "$listFile"

if [ $? = 0 ]
then
fcflog "INFO" "reading listFile					${GREEN}[OK]$NONE";
else
fcflog "ERROR" "reading listFile				${RED}[FAILED]$NONE";
echo "check permissions and if listFile exists!"
exit 1
fi

